### ISSUE TITLE
[1pt] Setting up the Kanban board

### ISSUE THREAD

**Issue by KIsmoilov** [abdallahmalima/Catalog-My-Things#22]
- Here is the link to our Github project https://github.com/abdallahmalima/Catalog-My-Things/projects/1 
- In our group there are 3 members.

Team member #1. @abdallahmalima 
Team member #2 @KIsmoilov 
Team member #3 @keebot-png

**Comment by pinkmoon25** [comment]
Hi @KIsmoilov @abdallahmalima  & @keebot-png , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
Kanban setup :heavy_check_mark: 
Equally Distributed :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
